apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '${{ values.serverPort }}'
    'backstage.io/kubernetes-id': '${{ values.name }}'
  name: ${{ values.name }}
  namespace: default
  labels:
    app: ${{ values.name }}
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - name: http
      port: ${{ values.serverPort }}
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
  namespace: default
  labels:
    app: ${{ values.name }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
      annotations:
        backstage.io/kubernetes-id: ${{ values.name }}
    spec:
      containers:
        - name: ${{ values.name }}
          image: ${{ values.name }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: ${{ values.serverPort }}